### ISSUE TITLE
Panicking on occasional PoisonError after delete()

### ISSUE THREAD

**Issue by busyboredom** [alexliesenfeld/httpmock#53]
Relevant logs: 

```
[2021-11-21T18:12:12Z DEBUG httpmock::server::web::handlers] Deleted mock with id=46
[2021-11-21T18:12:12Z DEBUG httpmock::server::web::handlers] Adding new mock with ID=48
[2021-11-21T18:12:12Z DEBUG httpmock::server::web::handlers] Deleted mock with id=45
[2021-11-21T18:12:12Z DEBUG httpmock::server::web::handlers] Adding new mock with ID=49
[2021-11-21T18:12:12Z DEBUG httpmock::server::web::handlers] Matched mock with id=45 to the following request: HttpMockRequest {

(request details omitted for brevity)

}
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/charlie/.cargo/registry/src/github.com-1ecc6299db9ec823/httpmock-0.6.4/src/server/web/handlers.rs:133:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/charlie/.cargo/registry/src/github.com-1ecc6299db9ec823/httpmock-0.6.4/src/server/web/handlers.rs:115:40
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/charlie/.cargo/registry/src/github.com-1ecc6299db9ec823/httpmock-0.6.4/src/server/web/handlers.rs:115:40
```

It doesn't happen often, maybe 1 in 10 times that I run my application's tests.

**Comment by alexliesenfeld** [comment]
Should be fixed with e6282b8.
